### PR TITLE
Test record property access (Fixes B-300)

### PR DESCRIPTION
**Pull request by aaronstanek**

### CODE REVIEW

**Review by Nick-Mazuk — CHANGES_REQUESTED** [review]
Sorry if the bug wasn't clear, but it was specifically to test accessing record properties _inside Buri_.

So for instance, consider the following Buri code:

```
@export
person = {
    name: "John",
    age: 36,
    eye_color: #brown
}

@export
name = person.name
```

The equivalent test would be:

```js
expect(Bname).toEqual(Bperson.name)
```

**Comment by aaronstanek** [comment]
Thank you for clarifying.

**Review by Nick-Mazuk — APPROVED** [review]

**Pull request closed without merging**
